In [102]:
import json
import pandas as pd
import os
from os import listdir
from os.path import isfile, join

base_path = "/data/data/_aux/va_med_city"

In [ ]:
'''

// JAVASCRIPT Code to extract the relevant entities from the website: 
// https://www.va.gov/directory/guide/rpt_fac_list.cfm

function getCity(input) {

	c = input.split("\n")[1]
	return c.substring(c.search(/\S|$/), c.indexOf(","))

}

function replaceAll(str, find, replace) {
    return str.replace(new RegExp(escapeRegExp(find), 'g'), replace);
}

function escapeRegExp(str) {
    return str.replace(/([.*+?^=!:${}()|\[\]\/\\])/g, "\\$1");
}

function cleanString(input){

	ret = replaceAll(input, "\t", "")
	ret = replaceAll(ret, "\n", "")
	
	return ret; 

}

output = []

var noticeMap = $('#rpt tbody tr').map(function() {
    var $cells = $(this).children();
if ($cells.length == 1){title = $cells.eq(0).text()}else{

	fac = cleanString($cells.eq(1).text());
	add = cleanString($cells.eq(2).text());

	elem = {
            category: title, 
            stationId: $cells.eq(0).text(),
            Facility: fac,
            Address: add,
			City: getCity($cells.eq(2).text()),
            State: $cells.eq(3).text(),
            Phone: $cells.eq(4).text()
			}

output.push(elem) 
    return elem;}
});


function download(content, fileName, contentType) {
	content = JSON.stringify(content)
    var a = document.createElement("a");
    var file = new Blob([content], {type: contentType});
    a.href = URL.createObjectURL(file);
    a.download = fileName;
    a.click();
}

fileName = $('#rpt thead th').text() + ".json"

download(output, fileName, 'text/plain');




'''

In [103]:
s = base_path + "/Veterans Health Administration_ VISN 9_ VA MidSouth Healthcare Network.json"
output_file = join(base_path, "lookup_va_med_city.csv")

if os.path.exists(output_file):
    os.remove(output_file)

In [104]:

files_list = []

for f in os.listdir(base_path):
    if isfile(join(base_path, f)):
        if f.endswith(".json"):
            files_list.append(f)

In [105]:
all_files = files_list

In [106]:
out = pd.DataFrame()

for f in all_files:
    s = base_path + "/" + f
    with open(s) as json_file:
        data = json.load(json_file)
        print("For file %s there are %s number of entries" % (f, len(data)))
        df = pd.DataFrame(data)
        out = out.append(df)

For file Veterans Health Administration_ VISN 16_ South Central VA Health Care Network.json there are 81 number of entries
For file Veterans Health Administration_ VISN 7_ VA Southeast Network.json there are 80 number of entries
For file Veterans Health Administration_ VISN 1_ VA New England Healthcare System.json there are 83 number of entries
For file Veterans Health Administration_ VISN 17_ VA Heart of Texas Health Care Network.json there are 77 number of entries
For file Veterans Health Administration_ VISN 10_ VA Healthcare System.json there are 113 number of entries
For file Veterans Health Administration_ VISN 4_ VA Healthcare - VISN 4.json there are 69 number of entries
For file Veterans Health Administration_ VISN 12_ VA Great Lakes Health Care System.json there are 70 number of entries
For file Veterans Health Administration_ VISN 15_ VA Heartland Network.json there are 78 number of entries
For file Veterans Health Administration_ VISN 6_ VA Mid-Atlantic Health Care Network.json there are 59 number of entries
For file Veterans Health Administration_ VISN 8_ VA Sunshine Healthcare Network.json there are 103 number of entries
For file Veterans Health Administration_ VISN 22_ Desert Pacific Healthcare Network.json there are 114 number of entries
For file Veterans Health Administration_ VISN 9_ VA MidSouth Healthcare Network.json there are 69 number of entries
For file Veterans Health Administration_ VISN 21_ Sierra Pacific Network.json there are 85 number of entries
For file Veterans Health Administration_ VISN 23_ VA Midwest Health Care Network.json there are 91 number of entries
For file Veterans Health Administration_ VISN 5_ VA Capitol Health Care Network.json there are 62 number of entries
For file Veterans Health Administration_ VISN 19_ Rocky Mountain Network.json there are 105 number of entries
For file Veterans Health Administration_ VISN 2_ New York_New Jersey VA Health Care Network.json there are 99 number of entries
For file Veterans Health Administration_ VISN 20_ Northwest Network.json there are 77 number of entries

In [107]:
df.head(5)

,category,stationId,Facility,Address,City,State,Phone
0,VISN,10N20,VISN 20: Northwest Network,"1601 4th Plain Blvd Building 17, 4th Floor, Su...",Vancouver,WA,360-619-5925
1,VA Health Care System,463,Alaska VA Healthcare System,"1201 North Muldoon Road Anchorage, AK 99504",Anchorage,AK,907-257-4700 Or 907-257-4700
2,VA Health Care System,648,VA Portland Health Care System,"3710 SW U.S. Veterans Hospital Road Portland,...",Portland,OR,503-220-8262 Or 800-949-1004
3,VA Health Care System,663,VA Puget Sound Health Care System,"1660 S. Columbian Way Seattle, WA 98108",Seattle,WA,206-762-1010 Or 206-762-1010
4,VA Health Care System,663A4,VA Puget Sound Health Care System - American L...,"9600 Veterans Dr Lakewood, WA 98493",Lakewood,WA,253-582-8440 Or 253-582-8440

In [108]:
out

,category,stationId,Facility,Address,City,State,Phone
0,VISN,10N16,VISN 16: South Central VA Health Care Network,"715 S. Pear Orchard Road Ridgeland, MS 39157 ...",Ridgeland,MS,601-206-6900
1,VA Medical Center,502,Alexandria VA Health Care System,"2495 Shreveport Hwy 71 N Pineville, LA 71360-...",Pineville,LA,318-473-0010
2,VA Medical Center,598,Central Arkansas Veterans Healthcare System Eu...,"2200 Fort Roots Drive North Little Rock, AR 7...",North Little Rock,AR,501-257-1000
3,VA Medical Center,598,Central Arkansas Veterans Healthcare System Jo...,"4300 West 7th Street Little Rock, AR 72205-5484",Little Rock,AR,501-257-1000
4,VA Medical Center,586,G.V. (Sonny) Montgomery VA Medical Center,"1500 E. Woodrow Wilson Avenue Jackson, MS 39216",Jackson,MS,601-362-4471
...,...,...,...,...,...,...,...
72,Vet Center,0541V,Walla Walla Vet Center,"1104 West Poplar Walla Walla, WA 99362",Walla Walla,WA,509-526-8387
73,Vet Center,0512V,Wasilla Vet Center,"851 E. West Point Drive Suite 102 Wasilla, AK...",Wasilla,AK,907-376-4318
74,Vet Center,0523,Yakima Valley Vet Center,"2119 W. Lincoln Ave Yakima, WA 98902",Yakima,WA,509-457-2736
75,,687,687,"77 Wainwright Drive Walla Walla, WA 99362",Walla Walla,WA,
76,,0523,Yakima Valley Vet Center,"2119 West Lincoln Avenue Yakima, WA 98902",Yakima,WA,509-457-2736

In [109]:
df_med_centers = out[out.category == 'VA Medical Center']

In [110]:
df_city_lookup = df_med_centers[["City", "State"]]
df_city_lookup = df_city_lookup.drop_duplicates()

In [111]:
df_city_lookup

                 City State
1           Pineville    LA
2   North Little Rock    AR
3         Little Rock    AR
4             Jackson    MS
5              Biloxi    MS
..                ...   ...
7         Walla Walla    WA
8             Spokane    WA
9            Roseburg    OR
10          Vancouver    WA
11         White City    OR

[132 rows x 2 columns]

In [112]:
df_city_lookup.to_csv(output_file, index = None, header=True)